export type Project = {
  id: number;
  project_code: string;
  project_name: string;
  developer_id: number | null;
  city_id: number;
  micromarket_id: number | null;
  locality_id: number | null;
  address_text: string | null;
  asset_class: string | null;
  project_stage: string | null;
  launch_date: string | null;
  expected_possession_date: string | null;
  total_land_acres: number | null;
  total_units: number | null;
  towers_count: number | null;
  floors_count: number | null;
  unit_mix_summary: Record<string, number> | Array<unknown> | null;
  avg_unit_size_sqft: number | null;
  density_units_per_acre: number | null;
  parking_ratio: number | null;
  open_space_pct: number | null;
  amenity_score: number | null;
  construction_quality_score: number | null;
  legal_clarity_score: number | null;
  rera_status: string | null;
  benchmark_current_asking_price: number | null;
  benchmark_radius_km: number | null;
  source: string | null;
  last_data_refreshed_at: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};