import { AnalysisFieldConfig, AnalysisFormValues } from "@/types/analysis-form";
import { Project } from "@/types/project";

export const analysisInputGroups: Array<{
  title: string;
  description: string;
  fields: AnalysisFieldConfig[];
}> = [
  {
    title: "Project basics",
    description:
      "Core identity and timeline fields that anchor the subject project before calculations begin.",
    fields: [
      {
        key: "project_name",
        label: "Project name",
        placeholder: "e.g. Sample Gurgaon Launch One",
        helpText: "Name of the project being analyzed.",
        inputType: "text",
        required: true,
      },
      {
        key: "project_stage",
        label: "Project stage",
        placeholder: "Select stage",
        helpText: "Launch stage affects construction risk and pricing premium assumptions.",
        inputType: "select",
        required: true,
        options: ["New Launch", "Pre-Launch", "Under Construction", "Ready to Move"],
      },
      {
        key: "rera_status",
        label: "RERA status",
        placeholder: "Select RERA status",
        helpText: "Unregistered projects carry a legal risk penalty in the engine.",
        inputType: "select",
        required: true,
        options: ["Registered", "Applied", "Exempted", "Not Registered"],
      },
      {
        key: "total_units",
        label: "Total units",
        placeholder: "e.g. 950",
        helpText: "Total residential units as per RERA approval.",
        inputType: "number",
        min: 10,
        max: 20000,
      },
      {
        key: "launch_date",
        label: "Launch date",
        placeholder: "YYYY-MM-DD",
        helpText: "Project launch timing influences time-based comparisons.",
        inputType: "date",
      },
      {
        key: "expected_possession_date",
        label: "Expected possession date",
        placeholder: "YYYY-MM-DD",
        helpText: "Possession timing influences stage discount and buyer confidence.",
        inputType: "date",
      },
    ],
  },
  {
    title: "Product and configuration",
    description:
      "Physical and product-level inputs that influence quality premium, density, and usability.",
    fields: [
      {
        key: "avg_unit_size_sqft",
        label: "Average unit size",
        placeholder: "e.g. 1850",
        helpText: "Typical average saleable or built-up unit size used for analysis.",
        inputType: "number",
        unit: "sq ft",
        min: 250,
        max: 15000,
      },
      {
        key: "density_units_per_acre",
        label: "Density",
        placeholder: "e.g. 76",
        helpText: "Units per acre. Higher density (>75) may affect perceived premium.",
        inputType: "number",
        unit: "units/acre",
        min: 5,
        max: 300,
      },
      {
        key: "parking_ratio",
        label: "Parking ratio",
        placeholder: "e.g. 1.7",
        helpText: "Parking slots per unit. Values above 1.5 typically add marginal premium.",
        inputType: "number",
        unit: "slots/unit",
        min: 0,
        max: 5,
      },
      {
        key: "open_space_pct",
        label: "Open space percentage",
        placeholder: "e.g. 68",
        helpText: "Share of open area in the overall project. Higher is better.",
        inputType: "number",
        unit: "%",
        min: 0,
        max: 100,
      },
      {
        key: "amenity_score",
        label: "Amenity score",
        placeholder: "e.g. 8.4",
        helpText: "0–10 score for amenities and lifestyle offering.",
        inputType: "number",
        unit: "score",
        min: 0,
        max: 10,
      },
      {
        key: "construction_quality_score",
        label: "Construction quality score",
        placeholder: "e.g. 8.8",
        helpText: "0–10 score for material quality and build standards.",
        inputType: "number",
        unit: "score",
        min: 0,
        max: 10,
      },
      {
        key: "legal_clarity_score",
        label: "Legal clarity score",
        placeholder: "e.g. 8.5",
        helpText: "0–10 score for title clarity and encumbrance status.",
        inputType: "number",
        unit: "score",
        min: 0,
        max: 10,
      },
      {
        key: "total_land_acres",
        label: "Total land area",
        placeholder: "e.g. 12.5",
        helpText: "Total site area for the project.",
        inputType: "number",
        unit: "acres",
        min: 0.1,
        max: 5000,
      },
      {
        key: "towers_count",
        label: "Towers count",
        placeholder: "e.g. 7",
        helpText: "Number of residential towers in the project.",
        inputType: "number",
        min: 1,
        max: 100,
      },
      {
        key: "floors_count",
        label: "Floors count",
        placeholder: "e.g. 34",
        helpText: "Average or representative tower height.",
        inputType: "number",
        min: 1,
        max: 100,
      },
    ],
  },
  {
    title: "Market and benchmark context",
    description:
      "Market-facing variables that shape fair asking price benchmarking and current positioning.",
    fields: [
      {
        key: "benchmark_current_asking_price",
        label: "Benchmark asking price",
        placeholder: "e.g. 18250",
        helpText: "Prevailing micromarket asking price. This is the baseline for all adjustments.",
        inputType: "number",
        unit: "₹/sq ft",
        required: true,
        min: 3000,
        max: 100000,
      },
      {
        key: "benchmark_radius_km",
        label: "Benchmark radius",
        placeholder: "e.g. 3",
        helpText: "Comparable search radius used for benchmark construction. Recommended: 2–3 km.",
        inputType: "number",
        unit: "km",
        min: 0.5,
        max: 10,
      },
      {
        key: "comparable_sold_psf",
        label: "Comparable sold price",
        placeholder: "e.g. 16500",
        helpText: "Secondary market / resale price for comparable projects nearby.",
        inputType: "number",
        unit: "₹/sq ft",
        min: 2000,
        max: 100000,
      },
      {
        key: "avg_rent",
        label: "Average monthly rent",
        placeholder: "e.g. 42000",
        helpText: "Representative rent for a comparable unit in the micromarket.",
        inputType: "number",
        unit: "₹/month",
        min: 5000,
        max: 500000,
      },
    ],
  },
  {
    title: "Supply and demand",
    description:
      "Supply-demand health indicators that affect near-term pricing power and projection drag.",
    fields: [
      {
        key: "inventory_overhang_months",
        label: "Inventory overhang",
        placeholder: "e.g. 18",
        helpText: "Months to absorb current supply at prevailing sales pace.",
        inputType: "number",
        unit: "months",
        min: 0,
        max: 120,
      },
      {
        key: "absorption_rate_pct",
        label: "Absorption rate",
        placeholder: "e.g. 55",
        helpText: "% of newly launched units sold within the first 6 months of launch.",
        inputType: "number",
        unit: "%",
        min: 0,
        max: 100,
      },
      {
        key: "new_supply_upcoming_units",
        label: "Upcoming new supply",
        placeholder: "e.g. 4500",
        helpText: "Total units expected to launch in the micromarket in the next 12 months.",
        inputType: "number",
        unit: "units",
        min: 0,
        max: 500000,
      },
    ],
  },
  {
    title: "Developer profile",
    description:
      "Developer-level quality, delivery track record, and litigation signals that drive premium or discount.",
    fields: [
      {
        key: "developer_brand_score",
        label: "Developer brand score",
        placeholder: "e.g. 8.5",
        helpText: "0–10 brand perception score. Score above 8 typically adds a 5–15% premium.",
        inputType: "number",
        unit: "score",
        min: 0,
        max: 10,
      },
      {
        key: "developer_on_time_score",
        label: "On-time delivery score",
        placeholder: "e.g. 8.0",
        helpText: "0–10 score for historical delivery track record. 10 = never delayed.",
        inputType: "number",
        unit: "score",
        min: 0,
        max: 10,
      },
      {
        key: "developer_litigation_score",
        label: "Litigation risk score",
        placeholder: "e.g. 3.0",
        helpText: "0–10 score for known litigation exposure. Higher = more risk.",
        inputType: "number",
        unit: "score",
        min: 0,
        max: 10,
      },
    ],
  },
  {
    title: "Macro inputs",
    description:
      "Macroeconomic variables that affect affordability, demand, and real price growth.",
    fields: [
      {
        key: "repo_rate_pct",
        label: "RBI repo rate",
        placeholder: "e.g. 6.5",
        helpText: "Current RBI repo rate. Higher rates increase affordability drag.",
        inputType: "number",
        unit: "%",
        min: 2,
        max: 15,
      },
      {
        key: "inflation_rate_pct",
        label: "CPI inflation rate",
        placeholder: "e.g. 5.2",
        helpText: "Current CPI inflation rate. High inflation erodes real demand growth.",
        inputType: "number",
        unit: "%",
        min: 0,
        max: 20,
      },
      {
        key: "gdp_growth_pct",
        label: "GDP growth rate",
        placeholder: "e.g. 6.8",
        helpText: "Expected annual GDP growth. Higher growth supports demand assumptions.",
        inputType: "number",
        unit: "%",
        min: -5,
        max: 15,
      },
    ],
  },
  {
    title: "Connectivity and infrastructure",
    description:
      "Key accessibility and planned infrastructure factors that affect pricing premium and forward projections.",
    fields: [
      {
        key: "distance_to_metro_km",
        label: "Distance to nearest metro",
        placeholder: "e.g. 1.8",
        helpText: "Road distance to the nearest operational or upcoming metro station.",
        inputType: "number",
        unit: "km",
        min: 0,
        max: 50,
      },
      {
        key: "distance_to_cbd_km",
        label: "Distance to CBD / IT hub",
        placeholder: "e.g. 8",
        helpText: "Road distance to the nearest major employment hub.",
        inputType: "number",
        unit: "km",
        min: 0,
        max: 100,
      },
      {
        key: "distance_to_airport_km",
        label: "Distance to airport",
        placeholder: "e.g. 18",
        helpText: "Road distance to the nearest domestic or international airport.",
        inputType: "number",
        unit: "km",
        min: 0,
        max: 150,
      },
      {
        key: "social_infra_score",
        label: "Social infra score",
        placeholder: "e.g. 7.1",
        helpText: "0–10 composite score for schools, hospitals, malls within 3 km.",
        inputType: "number",
        unit: "score",
        min: 0,
        max: 10,
      },
      {
        key: "infra_uplift_pct",
        label: "Infrastructure uplift factor",
        placeholder: "e.g. 4.5",
        helpText: "Estimated % price uplift from planned or UC infrastructure nearby.",
        inputType: "number",
        unit: "%",
        min: 0,
        max: 30,
      },
    ],
  },
  {
    title: "Scenario adjustments",
    description:
      "Growth scenario and custom rate override that drive all forward projection calculations.",
    fields: [
      {
        key: "scenario_code",
        label: "Growth scenario",
        placeholder: "Select scenario",
        helpText: "Bear = 4% CAGR · Base = 8% CAGR · Bull = 12% CAGR.",
        inputType: "select",
        required: true,
        options: ["bear", "base", "bull", "custom"],
      },
      {
        key: "custom_growth_rate_pct",
        label: "Custom annual growth rate",
        placeholder: "e.g. 9.5",
        helpText: "Only used when 'custom' scenario is selected. Enter your own CAGR.",
        inputType: "number",
        unit: "%",
        min: -10,
        max: 30,
      },
    ],
  },
];

export function buildInitialAnalysisFormValues(): AnalysisFormValues {
  return {
    project_name: "",
    city_id: null,
    micromarket_id: null,
    locality_id: null,
    project_stage: "",
    rera_status: "Registered",
    launch_date: "",
    expected_possession_date: "",
    total_units: "",

    total_land_acres: "",
    towers_count: "",
    floors_count: "",
    avg_unit_size_sqft: "",
    density_units_per_acre: "",
    parking_ratio: "",
    open_space_pct: "",
    amenity_score: "",
    construction_quality_score: "",
    legal_clarity_score: "",

    benchmark_current_asking_price: "",
    benchmark_radius_km: "",
    comparable_sold_psf: "",
    avg_rent: "",

    inventory_overhang_months: "",
    absorption_rate_pct: "",
    new_supply_upcoming_units: "",

    developer_brand_score: "",
    developer_on_time_score: "",
    developer_litigation_score: "",

    repo_rate_pct: "6.5",
    inflation_rate_pct: "5.0",
    gdp_growth_pct: "6.5",

    distance_to_metro_km: "",
    distance_to_airport_km: "",
    distance_to_cbd_km: "",
    social_infra_score: "",

    infra_uplift_pct: "",

    scenario_code: "base",
    custom_growth_rate_pct: "",
  };
}

function toStringValue(value: number | string | null | undefined): string {
  if (value === null || value === undefined) return "";
  return String(value);
}

export function buildAnalysisFormValuesFromProject(
  project: Project,
): AnalysisFormValues {
  return {
    project_name: project.project_name ?? "",
    city_id: project.city_id ?? null,
    micromarket_id: project.micromarket_id ?? null,
    locality_id: project.locality_id ?? null,
    project_stage: project.project_stage ?? "",
    rera_status: project.rera_status ?? "Registered",
    launch_date: project.launch_date ?? "",
    expected_possession_date: project.expected_possession_date ?? "",
    total_units: toStringValue(project.total_units),

    total_land_acres: toStringValue(project.total_land_acres),
    towers_count: toStringValue(project.towers_count),
    floors_count: toStringValue(project.floors_count),
    avg_unit_size_sqft: toStringValue(project.avg_unit_size_sqft),
    density_units_per_acre: toStringValue(project.density_units_per_acre),
    parking_ratio: toStringValue(project.parking_ratio),
    open_space_pct: toStringValue(project.open_space_pct),
    amenity_score: toStringValue(project.amenity_score),
    construction_quality_score: toStringValue(project.construction_quality_score),
    legal_clarity_score: toStringValue(project.legal_clarity_score),

    benchmark_current_asking_price: toStringValue(project.benchmark_current_asking_price),
    benchmark_radius_km: toStringValue(project.benchmark_radius_km),
    comparable_sold_psf: "",
    avg_rent: toStringValue(project.avg_rent),

    inventory_overhang_months: toStringValue(project.inventory_overhang_months),
    absorption_rate_pct: "",
    new_supply_upcoming_units: "",

    developer_brand_score: "",
    developer_on_time_score: "",
    developer_litigation_score: "",

    repo_rate_pct: "6.5",
    inflation_rate_pct: "5.0",
    gdp_growth_pct: "6.5",

    distance_to_metro_km: toStringValue(project.distance_to_metro_km),
    distance_to_airport_km: "",
    distance_to_cbd_km: "",
    social_infra_score: toStringValue(project.social_infra_score),

    infra_uplift_pct: "",

    scenario_code: "base",
    custom_growth_rate_pct: "",
  };
}
